[mgr]
prepend_keymap = [
    { on =  "H" , run = "tab_switch -1 --relative", desc = "Previous tab" },
    { on =  "L" , run = "tab_switch 1 --relative", desc = "Next tab" },
    { on = "q", run = "close", desc = "Close the current tab, or quit if it is last tab" },
]

