lastupdatecheck: 0
recentrepos:
- /Users/ice/projects/dotfiles
- /Users/ice/work2/fleetcontrol-app/feat-local
- /Users/ice/work2/fleetcontrol-app/feat-risk-driver-app
- /Users/ice/work/focaldata/fd-panel-supplier/CH-821
- /Users/ice/work/focaldata/pub-sub-wrapper/ch-833_create_wrapper_pub_sub
- /Users/ice/work/focaldata/raincloud-playground/master
- /Users/ice/work/focaldata/cin-questionnaire/CH-782
- /Users/ice/work/focaldata/cin-autobots/main/CH-782
- /Users/ice/projects/mql
- /Users/ice/work2/fleetcontrol-app/feat-risk-module
- /Users/ice/work/focaldata/fd-core-respondent/CH-768
- /Users/ice/work/focaldata/fd-core-respondent/CH-765
- /Users/ice/work/focaldata/cin-respondent/master
- /Users/ice/work/focaldata/fd-panel-supplier/CH-805
- /Users/ice/work2/fleetcontrol-app/feat-client-dashboard-map2.0
- /Users/ice/work/focaldata/fd-core-responses/CH-805
- /Users/ice/work/focaldata/fd-core-respondent/main
- /Users/ice/work/focaldata/cin-iac-application/add_sqlproxy_responses_panel
- /Users/ice/work/focaldata/cin-iac-manual/master
- /Users/ice/work/focaldata/fd-panel-supplier/main
- /Users/ice/work/focaldata/fd-core-respondent/CH-767
- /Users/ice/work/focaldata/fd-core-respondent/CH-764
- /Users/ice/work/focaldata/fd-core-respondent/CH-795
- /Users/ice/work/focaldata/fd-core-respondent/CH-794
- /Users/ice/work/focaldata/fd-core-respondent/CH-786
- /Users/ice/work/focaldata/fd-core-respondent/CH-713
- /Users/ice/work/focaldata/cin-autobots/main
- /Users/ice/work/focaldata/cin-iac-application/master
- /Users/ice/work/focaldata/fd-core-respondent/CH-717
- /Users/ice/work/focaldata/cin-fd-surveys/CH-749
- /Users/ice/work/focaldata/fd-template-service/main
- /Users/ice/work/focaldata/raincloud-playground/cint_openapi
- /Users/ice/work/focaldata/fd-core/main
- /Users/ice/work/focaldata/cin-respondent/CH-367
- /Users/ice/work/focaldata/fd-monitoring/main
- /Users/ice/work/focaldata/cin-respondent/CH-501
- /Users/ice/work/focaldata/cin-respondent/fork-demo
- /Users/ice/work/focaldata/cin-respondent/CH-638
- /Users/ice/work/focaldata/cin-respondent/CH-636
- /Users/ice/work/focaldata/cin-respondent/CH-631
- /Users/ice/projects/honeyposv2
- /Users/ice/projects/stamp_core
- /Users/ice/work/focaldata/cin-dashboard/CH-367
- /Users/ice/work/focaldata/cin-iac-application/CH-625
- /Users/ice/work/focaldata/cin-dashboard/main
- /Users/ice/work/focaldata/cin-respondent/CH-610
- /Users/ice/work/focaldata/cin-respondent/smoke
- /Users/ice/work/focaldata/cin-questionnaire/CH-501
- /Users/ice/work/focaldata/cin-dashboard/CH-501
- /Users/ice/work/focaldata/cin-loi-estimate/ch-557_migrating_to_artifact_registry
- /Users/ice/work/focaldata/fd-core-smoke-tests/CH-501
- /Users/ice/work/focaldata/cin-respondent/smoke_test
- /Users/ice/work/focaldata/cin-questionnaire/master
- /Users/ice/work/focaldata/fd-local
- /Users/ice/work/focaldata/cin-respondent/CH-471
- /Users/ice/work/focaldata/cin-questionnaire/test
- /Users/ice/projects/stamp
- /Users/ice/work/focaldata/cin-respondent/CH-590
- /Users/ice/work/focaldata/cin-dashboard/CH-502
- /Users/ice/work/focaldata/cin-respondent/CH-502
- /Users/ice/work/focaldata/cin-questionnaire/CH-502
- /Users/ice/work/focaldata/fd-monitoring/CH-575
- /Users/ice/work/focaldata/cin-questionnaire/test_smoke_Test
- /Users/ice/work/focaldata/fd-core-smoke-tests/main
- /Users/ice/work/focaldata/cin-respondent/CH-527
- /Users/ice/work/focaldata/cin-respondent/CH-513
- /Users/ice/work/focaldata/cin-respondent/CH-468
- /Users/ice/work/focaldata/cin-respondent/CH-521-split-quota-count-logic
- /Users/ice/work/focaldata/cin-respondent/CH-472
- /Users/ice/work/focaldata/cin-respondent/CH-530
- /Users/ice/work/focaldata/fd-respondent-app/main
- /Users/ice/work/focaldata/cin-respondent/CH-525
- /Users/ice/work/focaldata/cin-respondent/CH-469
- /Users/ice/work/focaldata/cin-survey-processing-pipeline
- /Users/ice/work/focaldata/auto-data-quality/main
- /Users/ice/work/focaldata/cin-questionnaire/CH-477
- /Users/ice/work/focaldata/cin-dashboard/CH-473
- /Users/ice/projects/nurture_go
- /Users/ice/work/focaldata/cin-questionnaire/CH-417
- /Users/ice/work/focaldata/fd-monitoring/CH-414
- /Users/ice/work/focaldata/cin-questionnaire/CH-367
- /Users/ice/work/focaldata/cin-respondent/CH-333/newRepoForResponseChoiceForPGDB
- /Users/ice/work/focaldata/cin-autobots/CH-413
- /Users/ice/work/focaldata/cin-questionnaire/CH-393
- /Users/ice/work/focaldata/cin-dashboard/CH-393
- /Users/ice/work/focaldata/cin-autobots/CIN-363
- /Users/ice/work/focaldata/cin-respondent/CH-345
- /Users/ice/work/focaldata/cin-questionnaire/CH-345
- /Users/ice/work/focaldata/cin-dashboard/CH-355-add-price-scaling
- /Users/ice/work/focaldata/cin-respondent/CH-356
- /Users/ice/projects/senior_go_dancing-pony-qxmcqs
- /Users/ice/work/focaldata/cin-autobots/CH-322
- /Users/ice/work/focaldata/cin-autobots/CH-281
- /Users/ice/work/focaldata/cin-dashboard/CH-305
- /Users/ice/work/focaldata/cin-dashboard/CH-222
- /Users/ice/work/focaldata/cin-respondent/CH-305
- /Users/ice/work/focaldata/fd-monitoring/CH-305
- /Users/ice/projects/cv
- /Users/ice/work/focaldata/cin-autobots/CH-280
- /Users/ice/work/focaldata/fd-monitoring/CH-280
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
