lastupdatecheck: 0
recentrepos:
- /Users/ice/projects/dotfiles
- /Users/ice/projects/stamp_core
- /Users/ice/work/focaldata/cin-dashboard/CH-355-add-price-scaling
- /Users/ice/work/focaldata/cin-respondent/CH-356
- /Users/ice/projects/senior_go_dancing-pony-qxmcqs
- /Users/ice/work/focaldata/cin-autobots/CH-322
- /Users/ice/work/focaldata/cin-autobots/CH-281
- /Users/ice/work/focaldata/cin-autobots/main
- /Users/ice/work/focaldata/cin-survey-processing-pipeline
- /Users/ice/projects/mql
- /Users/ice/work/focaldata/cin-dashboard/CH-305
- /Users/ice/work/focaldata/fd-core/main
- /Users/ice/work/focaldata/cin-dashboard/CH-222
- /Users/ice/work/focaldata/cin-respondent/CH-305
- /Users/ice/work/focaldata/fd-monitoring/main
- /Users/ice/work/focaldata/fd-monitoring/CH-305
- /Users/ice/projects/cv
- /Users/ice/work/focaldata/cin-autobots/CH-280
- /Users/ice/work/focaldata/fd-monitoring/CH-280
- /Users/ice/work/focaldata/cin-dashboard/main
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
