host: "0.0.0.0"
port: 8317
auth-dir: "~/.cli-proxy-api"

api-keys:
  - "key"

debug: false
request-retry: 3

routing:
  strategy: "fill-first"

quota-exceeded:
  switch-project: true
  switch-preview-model: true
