- name: Install Ghostty
  shell: |
    # Get the latest version from GitHub API
    ARCH=x86_64
    LATEST_URL=$(curl -s https://api.github.com/repos/pkgforge-dev/ghostty-appimage/releases/latest | grep "browser_download_url.*${ARCH}.AppImage\"" | cut -d '"' -f 4 | head -n 1)
    FILENAME=$(basename "$LATEST_URL")

    # Download the latest AppImage package
    wget "$LATEST_URL"

    # Make the AppImage executable
    chmod +x "$FILENAME"

    # Install for system wide availability
    sudo install "./$FILENAME" /usr/local/bin/ghostty

    # Remove the original AppImage file
    rm "$FILENAME"

  tags:
    - install
    - dotfiles
    - ghostty
