- name: Check if Homebrew is already installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed
  tags:
    - install
    - homebrew

- name: Create Homebrew directory
  become: true
  file:
    path: /home/linuxbrew/.linuxbrew
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  when: not brew_installed.stat.exists
  tags:
    - install
    - homebrew

- name: Install Homebrew
  become: false
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/bash
  environment:
    NONINTERACTIVE: "1"
  when: not brew_installed.stat.exists
  tags:
    - install
    - homebrew

- name: Add Homebrew to bashrc
  become: false
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    create: yes
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - homebrew

- name: Install Homebrew packages
  become: false
  community.general.homebrew:
    name:
      - bat
      - fzf
      - git-delta
      - lazygit
      - neovim
      - sst/tap/opencode
      - ripgrep
      - tlrc
      - uv
      - yazi
      - cliproxyapi
    state: present
    path: /home/linuxbrew/.linuxbrew/bin
  tags:
    - install
    - homebrew
    - packages

- name: Start cliproxyapi service
  become: false
  shell: /home/linuxbrew/.linuxbrew/bin/brew services start cliproxyapi
  register: cliproxyapi_service
  changed_when: "'Successfully started' in cliproxyapi_service.stdout"
  failed_when: false
  tags:
    - install
    - homebrew
