- name: Get Lunar vim repo
  git:
    repo: https://github.com/LunarVim/LunarVim.git
    dest: "{{ lookup('env', 'HOME') }}/LunarVim"
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
    - lvim

- name: Install Neovim and Lunar vim
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  shell: |
        cd {{ lookup('env', 'HOME') }}/
        ./LunarVim/utils/installer/install-neovim-from-release
        ./LunarVim/utils/installer/install.sh --no-install-dependencies -y
        rm -rf LunarVim
  args:
    executable: /bin/bash
  tags:
    - install
    - core
    - lvim
    - nvim

