- name: Check if Homebrew is installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew_check

- name: Install Neovim with Homebrew
  shell: /home/linuxbrew/.linuxbrew/bin/brew install neovim
  when: homebrew_check.stat.exists
  tags:
    - install
    - core
    - neovim

