- name: Install rustup
  shell: |
        set -o pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"
  tags:
    - install
    - dotfiles
    - rust
  become: false

- name: Add cargo env to fish config
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"
    line: 'source "$HOME/.cargo/env.fish"'
    create: yes
  when: ansible_facts['os_family'] != "Darwin"
  tags:
    - install
    - dotfiles
    - rust
