- name: Install sch, used to compile shell script
  shell: | 
        wget https://github.com/neurobin/shc/archive/refs/tags/4.0.3.tar.gz
        tar xvfz 4.0.3.tar.gz
        cd shc-4.0.3
        ./configure
        make
        make install
        cd ..
        rm -rf shc-4.0.3
        rm -rf xvfz 4.0.3.tar.gz
  args:
    executable: /bin/bash
  tags:
    - install
    - core
  become: true