- name: Download Stern
  unarchive:
    src: https://github.com/stern/stern/releases/download/v1.22.0/stern_1.22.0_linux_amd64.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    remote_src: yes

- name: Move Stern
  copy:
    src: "{{ lookup('env', 'HOME') }}/.local/bin/stern_1.22.0_linux_amd64/stern"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    mode: a+x

- name: Delete Stern download
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.local/bin/stern_1.22.0_linux_amd64"
