- name: Install Win32yank for WSL to allow for copy and paste
  become: true # sudo
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  shell: |
        # Get the latest release version
        curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
        unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
        chmod +x /tmp/win32yank.exe
        mv /tmp/win32yank.exe /usr/local/bin/
  args:
    executable: /bin/bash
  tags:
    - install
    - win32yank

