- name: Install Ubuntu Packages
  hosts: localhost

  pre_tasks:
  - name: Update Apt
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    become: true

  tasks:
    # this block of tasks will use sudo to install packages
    - block:
        # - include: tasks/k8.yaml

        - name: Install System Packages
          apt:
            name: ["zsh", "ffmpeg", "fzf", "bat", "ranger", "unzip", "zip", "tldr", "stow", "mpv", "tmux", "make", "python3-pip"]
          tags:
            - install
            - core
      become: true

    - include: tasks/neovim.yaml
    - include: tasks/lazygit.yaml
    # - include: tasks/kubectx.yaml
    # - include: tasks/stern.yaml

# docker example
# https://www.rechberger.io/tutorial-install-docker-using-ansible-on-a-remote-server/

# become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
#
