---
- name: Install MacOS Packages
  hosts: localhost

  vars:
    homebrew_installed_packages:
      - docker
      - docker-compose
      - jq
      - tmux
      - ffmpeg
      - fzf
      - kubectx
      - nvm
      - pyenv
      - ranger
      - stern
      - tldr
      - tmux
      - gnu-sed
      - bat
      - rustup
      - duti
      - kustomize
      - lazygit
      - k9s
      - shc
      - btop

    homebrew_cask_apps:
      - docker
      - firefox
      - google-chrome
      - brave-browser
      - slack
      - chromedriver
      - intellij-idea
      - mpv
      - onedrive
      - slack
      - zoom
      - firefox
      - google-cloud-sdk
      - iterm2
      - obs
      - postman
      - transmission
      - visual-studio-code
      - mailspring
      - onlyoffice
      - zotero
      - authy
      - derailed/k9s/k9s

  roles:
    - geerlingguy.mac.homebrew

  tasks:
    - name: Setup yabai
      file:
        src: ~/projects/dotfiles/configs/macos/.yabairc
        path: ~/
        state: hard
      tags:
        - install
        - core
        - yabai

    - name: Install rust
      shell: rustup-init
      args:
        executable: /bin/bash
      tags:
        - install
        - core
        - rust

    - include: tasks/mpv.yaml
