- name: Add all configurations
  hosts: localhost

  tasks:

    - stat:
        path: "{{ lookup('env', 'HOME') }}/.config/lvim/config.lua"
      register: link

    # only delete lvim config if it is a file and not a symbolic link
    - name: Remove LunarVim's config if it is not sym linked
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/lvim/config.lua"
        state: absent
      when: link.stat.islnk is defined and link.stat.islnk is not defined

    - name: Stow all config files
      shell: | 
          cd ../configs/
          stow -t "{{ lookup('env', 'HOME') }}" */
      args:
        executable: /bin/bash
      tags:
        - install
        - core

    - name: Install Lunar Vim plugins
      shell: lvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      args:
        executable: /bin/bash
      tags:
        - install
        - core

