---
# Install packages with sudo
- name: Install System Packages
  apt:
    name: [
        "wl-clipboard",
        "zsh",
        "ffmpeg",
        "unzip",
        "zip",
        "stow",
        "mpv",
        "make",
        "parallel",
        "tmux",
      ]
  become: true
  tags:
    - install
    - dotfiles
    - packages

- include_tasks: tasks/vscode.yaml
- import_tasks: tasks/homebrew.yaml
- import_tasks: tasks/rust.yaml
