---
# Update package cache before installing packages
- name: Update Apt
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  become: true

# Install packages with sudo
- name: Install System Packages
  apt:
    name:
      [
        "zsh",
        "ffmpeg",
        "fzf",
        "bat",
        "ranger",
        "unzip",
        "zip",
        "tldr",
        "stow",
        "mpv",
        "tmux",
        "make",
        "python3-pip",
        "parallel",
        "ripgrep",
        "delta",
        "kubectx",
      ]
  become: true
  tags:
    - install
    - core

- import_tasks: tasks/lazygit.yaml
- import_tasks: tasks/delta.yaml
- import_tasks: tasks/brave.yaml
# Commented tasks if you need them later
- import_tasks: tasks/rust.yaml
# - include_tasks: tasks/kubectx.yaml
# - include_tasks: tasks/stern.yaml
