---
- name: Install MacOS Packages

  vars:
    homebrew_installed_packages:
      - neovim
      - jq
      - tmux
      - ffmpeg
      - fzf
      - kubectx
      - nvm
      - pyenv
      - stern
      - tldr
      - tmux
      - gnu-sed
      - bat
      - rustup
      - duti
      - kustomize
      - lazygit
      - k9s
      - btop
      - ata
      - httpie
      - jira-cli
      - stow
      - git-delta
      - ruff
      - go
      - delve
      - parallel
      - bottom
      - goose
      - sst/tap/opencode
      - txn2/tap/kubefwd
      - openai-whisper

      - yazi # yazi, and it's dependencies
      - ffmpeg # for video thumbnails
      - sevenzip # for archive extraction and preview
      - jq # for JSON preview
      - poppler # for PDF preview
      - fd # for file searching
      - ripgrep # for file content searching
      - fzf # for quick file subtree navigation, >= 0.53.0
      - zoxide # for historical directories navigation, requires fzf
      - resvg # for SVG preview
      - imagemagick # for Font, HEIC, and JPEG XL preview
      - font-symbols-only-nerd-font

    homebrew_cask_apps:
      - docker
      - firefox
      - google-chrome
      - chromedriver
      - mpv
      - slack
      - zoom
      - firefox
      - obs
      - postman
      - transmission
      - onlyoffice
      - zotero
      - whatsapp
      - font-meslo-lg-nerd-font
      - ghostty
      - zen
      - raycast

    homebrew_taps:
      - ankitpokhrel/jira-cli

  roles:
    - geerlingguy.mac.homebrew

    - include_tasks: tasks/mpv.yaml
