---
# Install packages with sudo
- name: Install System Packages
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
    update_cache: true
  become: true
  tags:
    - install
    - dotfiles
    - packages

- include_tasks: tasks/vscode_arch.yaml
- import_tasks: tasks/homebrew.yaml
- import_tasks: tasks/nvm.yaml
- import_tasks: tasks/rust.yaml
- import_tasks: tasks/bun.yaml
