---
# Install packages with sudo
- name: Install System Packages
  apt:
    name:
      [
        "wl-clipboard",
        "zsh",
        "ffmpeg",
        "fzf",
        "bat",
        "unzip",
        "zip",
        "tldr",
        "stow",
        "mpv",
        "tmux",
        "make",
        "parallel",
        "ripgrep",
        "delta",
      ]
  become: true
  tags:
    - install
    - core

- import_tasks: tasks/homebrew.yaml
- import_tasks: tasks/neovim.yaml
- import_tasks: tasks/yazi.yaml
- import_tasks: tasks/ghostty_ubuntu.yaml
# - import_tasks: tasks/flatpak.yaml
- import_tasks: tasks/opencode.yaml
- import_tasks: tasks/lazygit.yaml
- import_tasks: tasks/delta.yaml
# Commented tasks if you need them later
- import_tasks: tasks/rust.yaml
# - include_tasks: tasks/kubectx.yaml
# - include_tasks: tasks/stern.yaml
