---
# Update package cache before installing packages
# - name: Update Apt
#   apt:
#     force_apt_get: true
#     update_cache: true
#     state: present
#   become: true

# Install packages with sudo
- name: Install System Packages
  apt:
    name:
      [
        "zsh",
        "ffmpeg",
        "fzf",
        "bat",
        "unzip",
        "zip",
        "tldr",
        "stow",
        "mpv",
        "tmux",
        "make",
        "python3-pip",
        "parallel",
        "ripgrep",
        "delta",
      ]
  become: true
  tags:
    - install
    - core

- import_tasks: tasks/yazi.yaml
- import_tasks: tasks/ghostty.yaml
- import_tasks: tasks/flatpak.yaml
- import_tasks: tasks/opencode.yaml
- import_tasks: tasks/lazygit.yaml
- import_tasks: tasks/delta.yaml
- import_tasks: tasks/brave.yaml
# Commented tasks if you need them later
- import_tasks: tasks/rust.yaml
# - include_tasks: tasks/kubectx.yaml
# - include_tasks: tasks/stern.yaml
