---
- name: Install MacOS Packages

  vars:
    homebrew_installed_packages:
      - neovim
      - jq
      - tmux
      - ffmpeg
      - fzf
      - kubectx
      - nvm
      - pyenv
      - stern
      - tldr
      - tmux
      - gnu-sed
      - bat
      - rustup
      - duti
      - kustomize
      - lazygit
      - k9s
      - btop
      - ata
      - httpie
      - jira-cli
      - stow
      - git-delta
      - ruff
      - go
      - delve
      - parallel
      - bottom
      - goose
      - sst/tap/opencode
      - lf

    homebrew_cask_apps:
      - docker
      - firefox
      - google-chrome
      - brave-browser
      - chromedriver
      - mpv
      - slack
      - zoom
      - firefox
      - obs
      - postman
      - transmission
      - onlyoffice
      - zotero
      - whatsapp
      - font-meslo-lg-nerd-font
      - ghostty
      - zen

    homebrew_taps:
      - ankitpokhrel/jira-cli

  roles:
    - geerlingguy.mac.homebrew

    # tasks:
    #   - name: Setup yabai
    #     file:
    #       src: ~/projects/dotfiles/configs/macos/.yabairc
    #       path: ~/
    #       state: hard
    #     tags:
    #       - install
    #       - core
    #       - yabai

    #  - name: Install rust
    #    shell: rustup-init
    #    args:
    #      executable: /bin/bash
    #    tags:
    #      - install
    #      - core
    #      - rust

    - include_tasks: tasks/mpv.yaml
